name: ReadTheDocs CI

on:
  push:
    branches:
    - master
    - release/*
    paths:
    - 'docs/**'
    - '.github/workflows/docs.yml'
  pull_request:
    paths:
    - 'docs/**'
    - '.github/workflows/docs.yml'

jobs:

  build-docs:
    name: Build ReadTheDocs
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Build
      run: |
        sudo apt update
        sudo apt install python3-pip python3-setuptools
        # GitHub CI installs pip3 and setuptools outside the path.
        # Update the path to include them and run.
        PATH=/home/runner/.local/bin:$PATH pip3 install --user -r ./docs/requirements.txt
        cd ./docs && PATH=/home/runner/.local/bin:$PATH SPHINXOPTS="-W" make html
